"""string fix

Revision ID: 30b29ae18809
Revises: 46145785bf85
Create Date: 2018-03-27 14:57:17.040607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b29ae18809'
down_revision = '46145785bf85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
