"""string fix2

Revision ID: 3d59d85413f2
Revises: 30b29ae18809
Create Date: 2018-03-27 14:58:15.611317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d59d85413f2'
down_revision = '30b29ae18809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'name',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
